version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: spring_vertx_postgres
    environment:
      POSTGRES_DB: spring_vertx_demo
      POSTGRES_USER: cynicdog
      POSTGRES_PASSWORD: cynicdog
    ports:
      - "5432:5432"

  app:
    image: ginsenglee/spring-vertx-jib-app:0.0.1-SNAPSHOT
    container_name: spring_vertx_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring_vertx_demo
      SPRING_DATASOURCE_USERNAME: cynicdog
      SPRING_DATASOURCE_PASSWORD: cynicdog
    depends_on:
      - postgres

