package io.github.cynicdog.springvertxjibintegration.utils;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;

@Component
public class DatabaseInit implements CommandLineRunner {

    @Autowired
    private EntityManagerFactory entityManagerFactory;

    @Override
    public void run(String... args) {
        EntityManager entityManager = entityManagerFactory.createEntityManager();
        EntityTransaction transaction = entityManager.getTransaction();

        try {
            transaction.begin();

            entityManager.createNativeQuery("DROP TABLE IF EXISTS users").executeUpdate();
            entityManager.createNativeQuery("CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL)").executeUpdate();

            entityManager.createNativeQuery("INSERT INTO users (name) VALUES ('Alice')").executeUpdate();
            entityManager.createNativeQuery("INSERT INTO users (name) VALUES ('Bob')").executeUpdate();
            entityManager.createNativeQuery("INSERT INTO users (name) VALUES ('Charlie')").executeUpdate();

            transaction.commit();
        } catch (Exception e) {
            if (transaction.isActive()) {
                transaction.rollback();
            }
            e.printStackTrace();
        } finally {
            entityManager.close();
        }
    }
}
