name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:  
      POSTGRES_DB: spring_vertx_demo
      POSTGRES_USER: cynicdog
      POSTGRES_PASSWORD: cynicdog

    # Use the Postgres Docker service for initializing the Spring Boot application during Maven packaging.
    # This ensures that the application can connect to a PostgreSQL database for testing or setup
    # purposes while building the Docker image.
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: $POSTGRES_DB
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ env.POSTGRES_USER }}"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          mvn compile jib:build

      - name: Clean and Package Application
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${{ env.POSTGRES_DB }}
          SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
          SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
        run: |
          mvn clean package -DskipTests

      - name: Upload Manifests as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k8s-manifests
          path: target/classes/META-INF/dekorate/
